<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:wmc="http://www.opengis.net/context" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xlink="http://www.w3.org/1999/xlink">
<!--
Description: Convert a WFS Capabilities document to a Web Map Context
Author:      Nedjo Rogers nedjo AT gworks.ca
Licence:     GPL as per: http://www.gnu.org/copyleft/gpl.html

$Id: WMSCapabilities2Context.xsl,v 1.7 2005/05/19 20:50:32 madair1 Exp $
$Name:  $

-->
  <xsl:output method="xml"/>

  <xsl:param name="wmsVersion" select="/WMT_MS_Capabilities/@version"/>    
  <xsl:param name="wmsTitle" select="/WMT_MS_Capabilities/Service/Title"/>    
  <xsl:param name="wmsOnlineResource" select="/WMT_MS_Capabilities/Capability/Request/GetMap/DCPType/HTTP/Get/OnlineResource/@xlink:href"/>    
  <xsl:param name="wmsSrs" select="/WMT_MS_Capabilities/Capability/Layer/SRS"/>    
  <xsl:param name="width">180</xsl:param>

  <xsl:template match="/WMT_MS_Capabilities">
    <ViewContext version="1.0.0"
			    id="autoGeneratedContext_"
          xmlns="http://www.opengis.net/context">
      <General>
        <Title><xsl:value-of select="Service/Title"/></Title>
        <!-- TBD: The following should be extracted -->
        <xsl:variable name="minx" select="number(Capability/Layer/LatLonBoundingBox/@minx)"/>
        <xsl:variable name="maxx" select="number(Capability/Layer/LatLonBoundingBox/@maxx)"/>
        <xsl:variable name="miny" select="number(Capability/Layer/LatLonBoundingBox/@miny)"/>
        <xsl:variable name="maxy" select="number(Capability/Layer/LatLonBoundingBox/@maxy)"/>
        <xsl:variable name="dy" select=" $maxy - $miny "/>
        <xsl:variable name="dx" select=" $maxx - $minx "/>
        <xsl:variable name="height" select="round(($dy div $dx)*$width)"/>
        <Window width="{$width}" height="{$height}"/>
        <BoundingBox SRS="EPSG:4326" minx="{$minx}" miny="{$miny}" maxx="{$maxx}" maxy="{$maxy}"/>
      </General>
      <LayerList>
        <xsl:apply-templates select="Capability/Layer/Layer"/>
      </LayerList>
    </ViewContext>
  </xsl:template>

  <!-- Layer -->
  <xsl:template match="Layer">
    <xsl:element name="Layer" namespace="http://www.opengis.net/context">
      <xsl:attribute name="queryable">
        <xsl:value-of select="@queryable"/>
      </xsl:attribute>
      <xsl:attribute name="hidden">
        <xsl:text>0</xsl:text>
      </xsl:attribute>
      <xsl:element name="Server" namespace="http://www.opengis.net/context">
        <xsl:attribute name="service">
          <xsl:text>OGC:WMS</xsl:text>
        </xsl:attribute>
        <xsl:attribute name="version">
          <xsl:value-of select="$wmsVersion"/>
        </xsl:attribute>
        <xsl:attribute name="title">
          <xsl:value-of select="$wmsTitle"/>
        </xsl:attribute>
        <xsl:element name="OnlineResource" namespace="http://www.opengis.net/context">
          <xsl:attribute name="type">
            <xsl:text>simple</xsl:text>
          </xsl:attribute>
          <xsl:attribute name="xlink:href">
            <xsl:value-of select="$wmsOnlineResource"/>
          </xsl:attribute>
        </xsl:element>
      </xsl:element>
        <Name xmlns="http://www.opengis.net/context"><xsl:value-of select="Name"/></Name>
        <Title xmlns="http://www.opengis.net/context"><xsl:value-of select="Title"/></Title>
        <Abstract xmlns="http://www.opengis.net/context"><xsl:value-of select="Abstract"/></Abstract>
        <SRS xmlns="http://www.opengis.net/context">
          <xsl:choose>
            <xsl:when test="SRS"><xsl:value-of select="SRS"/></xsl:when>
            <xsl:otherwise><xsl:value-of select="$wmsSrs"/></xsl:otherwise>
          </xsl:choose>
        </SRS>
        <FormatList xmlns="http://www.opengis.net/context">
        	<Format current="1" xmlns="http://www.opengis.net/context">image/png</Format>
        </FormatList>
        <StyleList xmlns="http://www.opengis.net/context">
          <Style xmlns="http://www.opengis.net/context" current="1">
            <xsl:copy-of select="Style/*"/>
          </Style>
        </StyleList>
    </xsl:element>
  </xsl:template>
  
</xsl:stylesheet>