<hr>
<p>
<table width="100%">
<tr>
<td>
<a href="http://sourceforge.net/projects/mapbuilder"><img
src="http://sourceforge.net/sflogo.php?group_id=35246" width="88" height="31"
border="0" alt="Developed under SourceForge"></a>
</td><td>
<a href="http://geotools.sourceforge.net"><img
src="http://www.ccg.leeds.ac.uk/geotools/demos/linked/geotools.jpg"
alt="Powered by Geotools" width="116" height="24" align="middle"
border="0"></a>
</td><td>
<a href="http://mapserver.gis.umn.edu">mapserv</a>
</td><td>
<a href="http://postgis.refractions.net/">PostGIS</a>
</td>
</tr>
</table>
</p>
