<table width="100%" bgcolor="99FFCC" cellpadding="5" cellspacing="0" border="0">
<tr><td>
<h1>Community Map Builder</h1>
<p><em>Empowering communities to build and share geographic maps.</em>.</p>
<a href="index.shtml">Home</a>&nbsp;&nbsp;
<a href="about.shtml">About</a>&nbsp;&nbsp;
<a href="design.shtml">Design</a>&nbsp;&nbsp;
<a href="development.shtml">Development</a>&nbsp;&nbsp;
</td>
<td align="right"><img src="images/frog.gif"></td>
</tr>
</table>
<br>
